update_docker_stacks:
  - etherpad
  - gitea
  - hedgedoc
  - identity-provider
  - infrastructure
  - jenkins
  - kanboard
  - onlyoffice
  - homepage
  - forgejo
update_image_versions:
  - dir: identity-provider
    container: authentik
    image: ghcr.io/goauthentik/server
    tag: "{{ versions.authentik }}"
  - dir: infrastructure
    container: traefik
    image: traefik
    tag: "{{ versions.traefik }}"
  - dir: infrastructure
    container: portainer
    image: portainer/portainer-ce
    tag: latest
  - dir: kanboard
    container: kanboard
    image: kanboard/kanboard
    tag: "{{ versions.kanboard }}"
  - dir: etherpad
    container: etherpad
    image: etherpad/etherpad
    tag: "{{ versions.etherpad }}"
  - dir: stalwart
    container: mailserver
    image: stalwartlabs/stalwart
    tag: "{{ versions.stalwart }}"
  - dir: forgejo
    container: forgejo
    image: codeberg.org/forgejo/forgejo
    tag: "{{ versions.forgejo }}"
